Updated logger
KudAndrii/A_Level pull request #10
Opened 2022-05-23 17:49 UTC by KudAndrii

2022-05-25 15:30 UTC, DmytroZhuravlov14 requested changes

2022-05-25 15:30 UTC, DmytroZhuravlov14 commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +        private static readonly Lazy<FileService> Lazy = new Lazy<FileService>(()
Whats Lazy and why we need this here?

2022-05-25 15:30 UTC, DmytroZhuravlov14 commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +            if (Directory.GetFiles(_path).Length < 3)
return Directory.GetFiles(_path).Length < 3

2022-05-25 15:30 UTC, DmytroZhuravlov14 commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +            // "C:\Users\cudan\Documents\GitHub\A_Level\UpdatedLogger\UpdatedLogger\Logs\23.05.2022 20.04.20.txt"
this should not be here 4sure

2022-05-25 15:30 UTC, DmytroZhuravlov14 commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +            {
Why do we need this empty code block?

2022-05-25 17:34 UTC, KudAndrii commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +        private static readonly Lazy<FileService> Lazy = new Lazy<FileService>(()
This is realization of pattern singleton, and we use it here because this class works with files, not logger.

2022-05-25 17:42 UTC, KudAndrii commented on UpdatedLogger/UpdatedLogger/Configs/config.json
> +"..\\..\\..\\Logs\\"
file renamed

2022-05-25 17:51 UTC, KudAndrii commented on UpdatedLogger/UpdatedLogger/Configs/ConfigService.cs
> +            // return "..\\..\\..\\Logs\\";
unnecessary comments deleted

2022-05-25 17:51 UTC, KudAndrii commented on UpdatedLogger/UpdatedLogger/FileServices/FileService.cs
> +            // "C:\Users\cudan\Documents\GitHub\A_Level\UpdatedLogger\UpdatedLogger\Logs\23.05.2022 20.04.20.txt"
unnecessary comments deleted

2022-05-26 06:25 UTC, DmytroZhuravlov14 commented on UpdatedLogger/UpdatedLogger/Configs/config.json
> +"..\\..\\..\\Logs\\"
I meant a different thing - json format includes naming for the included properties, like this:
"SortAs": "SGML", so please add a parameter name for your parameter like "DirectoryName", etc.

2022-06-02 18:56 UTC, merged