Phone book
KudAndrii/A_Level pull request #13
Opened 2022-06-05 17:48 UTC by KudAndrii

2022-06-08 05:36 UTC, DmytroZhuravlov14 requested changes

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/AlphabetsJS/AlphabetConfig.json
> +  "AlphabetEN": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
Approach doesnt seem to be extensible, since some other configuration stuff can be added to the config. Or it expected to be another file then?

Good approach is to do like the following



"Langs": {
    "DefaultCulture": "en_US",
    "Alphabets": {
      "en_US": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      "ru_RU": "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"
    } (also adding explicit instance of the default culture)

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Enums/Names.cs
> +    public enum Names
No need them to be enums, just create the list of contacts in the entry point (starter/runner/etc
)

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Enums/Names.cs
> +    public enum Names
No need them to be enums, just create the list of contacts in the entry point (starter/runner/etc
)

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Enums/Surnames.cs
> +    public enum Surnames
same

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Enums/Surnames.cs
> +    public enum Surnames
same

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Services/ContactsServices.cs
> +            contacsArray[length - 1] = new Contact(((Names)_random.Next(0, 9)).ToString(), "911", _random.Next(600000000, 999999999));
Some strange magic numbers scare me in such a non complicated context field. Either add a comment or - better approach -> rework the flow + extract the numbers as a private fields

2022-06-08 05:36 UTC, DmytroZhuravlov14 commented on PhoneBook/PhoneBook/Services/ContactsServices.cs
> +            contacsArray[length - 1] = new Contact(((Names)_random.Next(0, 9)).ToString(), "911", _random.Next(600000000, 999999999));
Some strange magic numbers scare me in such a non complicated context field. Either add a comment or - better approach -> rework the flow + extract the numbers as a private fields

2022-06-08 13:48 UTC, KudAndrii commented on PhoneBook/PhoneBook/Services/ContactsServices.cs
> +            contacsArray[length - 1] = new Contact(((Names)_random.Next(0, 9)).ToString(), "911", _random.Next(600000000, 999999999));
Intermediate variables, and comments for them added.

2022-06-08 14:06 UTC, KudAndrii commented on PhoneBook/PhoneBook/Enums/Names.cs
> +    public enum Names
List created.

2022-06-09 19:51 UTC, KudAndrii commented on PhoneBook/PhoneBook/AlphabetsJS/AlphabetConfig.json
> +  "AlphabetEN": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
fixed.

2022-06-17 15:34 UTC, merged