Internet shop
KudAndrii/A_Level pull request #7
Opened 2022-05-13 16:22 UTC by KudAndrii

2022-05-14 07:04 UTC, DmytroZhuravlov14 requested changes

2022-05-14 07:04 UTC, DmytroZhuravlov14 commented on InternetShop/InternetShop/Cart.cs
> +    internal class Cart
Cart contains ShoppingCart - looks wierd a bit. Expected for Cart to contain other types of carts?))

2022-05-14 07:04 UTC, DmytroZhuravlov14 commented on InternetShop/InternetShop/IProduct.cs
> +    internal interface IProduct
Not sure we already know aboout the interfaces. Anyway, interfaces should be in a separate folder, as enums, services and models

2022-05-19 09:28 UTC, DmytroZhuravlov14 approved these changes

2022-05-19 09:28 UTC, DmytroZhuravlov14 commented on InternetShop/InternetShop/ShopCore/ShopService.cs
> +        public void AddProduct(List<Product> productRange, ref OrderFormation orderFormation, string input)
For what reasons do we need ref here?

2022-05-19 09:28 UTC, DmytroZhuravlov14 commented on InternetShop/InternetShop/Program.cs
> +            new ShopInterface().ShopMenu(ProductRange.Instance.Products);
How do you think - would we need this new instance of shopInterface in future? IF so, create a separate variable above and use it further

2022-05-19 09:40 UTC, KudAndrii commented on InternetShop/InternetShop/Program.cs
> +            new ShopInterface().ShopMenu(ProductRange.Instance.Products);
For now - no, but if situation changes - we can correct it very simple - write it to variable.
You mean it, don't you?

2022-05-19 14:58 UTC, KudAndrii commented on InternetShop/InternetShop/ShopCore/ShopService.cs
> +        public void AddProduct(List<Product> productRange, ref OrderFormation orderFormation, string input)
You are right, it is unnessessary

2022-05-21 13:23 UTC, merged

2022-05-23 06:35 UTC, DmytroZhuravlov14 commented on InternetShop/InternetShop/Program.cs
> +            new ShopInterface().ShopMenu(ProductRange.Instance.Products);
Fine for now, just asking +_+